CREATE USER products_db WITH PASSWORD 'password';
GRANT ALL PRIVILEGES ON DATABASE products_db TO products_db;
GRANT CONNECT ON DATABASE products_db TO products_db;
GRANT USAGE ON SCHEMA public TO products_db;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO products_db;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO products_db;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO products_db;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO products_db; 



CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- CREATE TABLE IF NOT EXISTS public.products